breakout_period = 55 # 55
exit_period = 20

sma_fast = 50
sma_slow = 200

atr_period = 15
adx_period = 14

volume_period = 10 # 50
volume_factor = 1.5 # 1.5

relative_strength_months = 6
top_percent = 25

# Near Breakout Settings
near_breakout_distance = 2.0
near_breakout_min_adx = 20.0
near_breakout_max_rs_rank = 125

# Initial Stop Loss
atr_stop_multiplier = 2.0
